version: '3.8'

services:
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: demo-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DEMO_MODE=true
      - AWS_REGION=us-west-2
      - FLASK_DEBUG=false
      - BACKEND_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - demo-network

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: demo-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

# Optional: Add volumes for development
# volumes:
#   backend_data:
#   frontend_data:
